const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../web/app.js','utf8');
const code=source.slice(source.indexOf("let trafficNodeId = ''"),source.indexOf('function protocolTable('));
let html='';
const good={protocol:'snell-v6',core:'xray',port:1000,traffic_state:'ready',users:[{name:'a',used:100,quota:1000,reset_day:1},{name:'b',used:200,quota:0}]};
const unknown={protocol:'ss2022',core:'singbox',port:2000,traffic_state:'unsupported',users:[{name:'c',used:0,quota:0}]};
const ctx=vm.createContext({nodes:[{id:'a',name:'服务器一',status:'online',snapshot:{instances:[good,unknown],metrics:{network_rx:100,network_tx:200}}}],names:{'snell-v6':'Snell v6',ss2022:'SS2022'},shell:s=>html=s,bytes:n=>`${n} B`,esc:s=>String(s),badge:s=>s,date:()=>'-',icon:()=>''});
vm.runInContext(code,ctx);
assert.equal(ctx.trafficUsage(good).value,300);
assert.equal(ctx.trafficUsage(unknown).value,null);
assert.equal(ctx.trafficUsage({...good,traffic_state:'unavailable',users:[]}).value,null);
assert.equal(ctx.trafficUsage({...good,traffic_state:'ready',users:[{used:0}]}).value,0);
assert.equal(ctx.trafficTotal([good,unknown]).value,300);
assert.equal(ctx.trafficTotal([good,unknown]).partial,true);
assert.equal(ctx.trafficTotal([]).value,null);
assert.equal(ctx.trafficStatus(good,{status:'offline'}),'离线快照');
ctx.trafficPage();
for(const text of ['服务器流量','协议流量','用户流量','300 B','900 B','暂不支持统计','每月 1 日重置']) assert(html.includes(text),text);
ctx.nodes=[];ctx.trafficPage();assert(html.includes('暂无服务器'));
console.log('PASS traffic aggregation, unknown vs zero, partial totals, offline snapshots, quotas and empty state');
